allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
    tasks.whenTaskAdded { task ->
        if (task.name.contains("AarMetadata")) {
            task.enabled = false
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}